# Params and toggles for RC controller drive including gain, rates, etc.
# Dummy values for now
motor_node:
  ros__parameters:
    max_linear_speed: 5.0      # m/s
    max_angular_speed: 3.0     # rad/s
    motor_timeout: 1.0         # seconds
    max_accel: 3.0             # m/s^2
    max_steering: 25           # degrees
    max_speed_straight: 30.0   # m/s | max speed on straights
    max_speed_turning: 15.0    # m/s | speed while completing turns
    simulation_mode: false     # set in motor node