# Params and toggles for gps node
gps_node:
  ros__parameters:
    gps_frequency: 10 # Hz
    serial_device: "/dev/ttyTHS1"
    baud_rate: 230400
    lat0: 40.4376975222 # In west lafayette
    lon0: -86.9444409756
    # VTG (course / ground-speed) uncertainty
    vtg_speed_sigma_mps: 0.1
    vtg_min_speed_for_yaw: 0.5