# Params and toggles for RC controller drive including gain, rates, etc.
motor_node:
  ros__parameters:
    max_linear_speed: 5.0      # m/s
    max_angular_speed: 3.0     # rad/s
    motor_timeout: 1.0         # seconds