# Planner configs including perception thresholds, toggles, etc.
pathfinder_node:
  ros__parameters:
    # Manual mode
    max_speed: 50
    acceleration: 0.2
    max_steering: 10
    steering_accel: 0.05
    line_path: /ws/data/racing_line/line.csv
    
    # Auto mode (Nav2 params)
    wheelbase_m: 1.05          # kart wheelbase in meters (rear axle -> front axle)
    v_max_mps: 15.0            # kart max speed in m/s (used for %<->m/s conversion)
    steer_max_deg: 25.0        # physical max front-wheel steering angle (degrees)
    
    use_velocity_scaled_lookahead: true  # Nav2: use_velocity_scaled_lookahead_dist
    lookahead_time_s: 1.0                # Nav2: lookahead_time (s)
    min_lookahead_m: 2.0                 # Nav2: min_lookahead_dist (m)
    max_lookahead_m: 3.0                 # Nav2: max_lookahead_dist (m)
    
    use_curvature_regulation: true       # Nav2: use_regulated_linear_velocity_scaling
    min_radius_m: 2.0                    # Nav2: regulated_linear_scaling_min_radius (m)
    min_reg_speed_pct: 0.20              # like regulated_linear_scaling_min_speed / v_max
    
    approach_dist_m: 1.0                 # Nav2: approach_velocity_scaling_dist (m)
    min_approach_speed_pct: 0.05         # like min_approach_linear_velocity / v_max
    