"""
NORMAL  : track racing line inside the corridor
FAILSAFE: stale state / no feasible plan

Solves every pathfinder tick (60 Hz) by rolling out K random control
sequences with the kinematic bicycle model and picking the lowest-cost
sequence whose trajectory stays inside the corridor. When the kart
strays outside the corridor, the shared DynamicLineManager swaps in a
cubic-Bezier overlay (RejoinStrategy) as the reference line so the
solver can plan back onto the racing line without a separate mode.
"""

import math
import time
from collections import deque
from typing import Optional, Tuple

import numpy as np
from std_msgs.msg import Float32MultiArray

from autonomous_kart.nodes.pathfinder.dynamic_line import (
    DynamicLineManager, KartState,
)
from autonomous_kart.nodes.pathfinder.planners.base import (
    KartConstants, Planner, PlannerInputs,
)
from autonomous_kart.nodes.pathfinder.planners.mpc_residual import (
    NUM_STEER_HIST, NUM_THROTTLE_HIST, ResidualLearner, _features,
)
from autonomous_kart.nodes.pathfinder.strategies.rejoin import RejoinStrategy

MODE_NORMAL, MODE_FAILSAFE = 0, 2


def _wrap(angle):
    """Wrap to (-pi, pi] — works on scalars or numpy arrays."""
    return (angle + math.pi) % (2.0 * math.pi) - math.pi


class MPCPlanner(Planner):
    name = "mpc"

    def __init__(self, params: dict, kart: KartConstants, racing_line: list,
                 logger=None, node=None):
        super().__init__(params, kart, racing_line, logger, node=node)

        if not racing_line:
            raise ValueError("MPCPlanner requires a non-empty racing line")

        g = params.get  # canonical yaml -> code; defaults below are fallbacks only

        # Horizon / sampling
        self.N = int(g("horizon_steps", 20))
        self.dt = float(g("dt_s", 0.05))
        self.K = int(g("num_samples", 48))
        self.steer_sigma = math.radians(float(g("steer_sigma_deg", 6.0)))
        self.accel_sigma = float(g("accel_sigma_mps2", 1.0))
        self.proj_back = int(g("proj_window_back", 5))
        self.proj_fwd = int(g("proj_window_fwd", 60))
        self.v_window_s = float(g("frenet_v_window_s", 0.3))
        # Threshold (m^2) above which the windowed Frenet match is considered
        # unreliable and _frenet falls back to a full-line nearest search.
        self._resync_dist2 = float(g("frenet_resync_m", 5.0)) ** 2

        # Physical limits pulled from kart constants (kart-wide /**: block —
        # no duplicates lurking in the mpc block).
        self.steer_max = math.radians(kart.steer_max_deg)
        self.steer_rate_max = math.radians(kart.steer_rate_max_degps)
        self.v_max = kart.v_max_mps
        self.wheelbase = kart.wheelbase_m
        self.a_min = kart.a_min_mps2
        self.a_max = kart.a_max_mps2
        self.a_lat_max = kart.a_lat_max_mps2
        self.target_speed = float(g("target_speed_mps", 6.0))

        # Corridor (centerline = racing line)
        tw = float(g("track_half_width_m", 2.5))
        sm = float(g("safety_margin_m", 0.5))
        kw = float(g("kart_half_width_m", 0.5025))
        self.corridor_half = tw - sm - kw

        # Costs
        self.w_d = float(g("w_d", 100.0))
        self.w_heading = float(g("w_heading", 30.0))
        self.w_speed = float(g("w_speed", 5.0))
        self.w_delta = float(g("w_delta", 5.0))
        self.w_drate = float(g("w_delta_rate", 50.0))
        self.w_accel = float(g("w_accel", 2.0))
        self.w_boundary = float(g("w_boundary", 1000.0))
        self.w_progress = float(g("w_progress", 1.0))
        self.w_term_d = float(g("w_terminal_d", 200.0))
        self.w_term_h = float(g("w_terminal_heading", 100.0))
        self.w_a_lat = float(g("w_a_lat", 50.0))

        # Inner-corridor "stay centered" barrier: zero inside
        # edge_inner_frac * corridor_half of the line, quadratic outward.
        # Separate from w_d (flat quadratic everywhere) so the planner can be
        # gently centered without being whipped to the centerline in corners.
        self.w_edge = float(g("w_edge", 200.0))
        self.edge_inner_frac = float(g("edge_inner_frac", 0.5))
        self.edge_inner = self.corridor_half * self.edge_inner_frac

        # Failsafe / feasibility sentinels
        self.max_failures = int(g("max_consecutive_solver_failures", 3))
        self.infeasible_cost = float(g("infeasible_cost", 1.0e9))
        self.feasibility_threshold = float(g("feasibility_threshold", 5.0e8))

        # Rejoin: cubic-Bezier overlay generated by RejoinStrategy through the
        # shared DynamicLineManager. When CTE exceeds the activation gate the
        # manager swaps in a bezier from the kart's pose back onto the racing
        # line; the planner Frenet-projects against that bezier (treating it
        # as the reference line) until it deactivates near the merge point.
        self.line_manager = DynamicLineManager(racing_line, logger=logger)
        self.line_manager.register(RejoinStrategy(
            cte_activate=float(g("rejoin_cte_activate", 2.5)),
            cte_deactivate=float(g("rejoin_cte_deactivate", 1.0)),
            merge_lookahead_m=float(g("rejoin_merge_lookahead_m", 15.0)),
            min_turning_radius=float(g("rejoin_min_turning_radius", 3.0)),
        ))

        # Racing line as flat numpy arrays with derived tangent for Frenet.
        # The static racing line is built once; `self.l_*` references the
        # currently active reference (static line or bezier overlay) and is
        # swapped each tick by _set_active_line.
        self._static_arrays = self._build_line_arrays(racing_line)
        self._bezier_arrays = None
        self._set_active_line(self._static_arrays)

        # State carried between ticks
        self.closest_idx = 0           # idx into the ACTIVE reference (line or bezier)
        self.static_closest_idx = 0    # idx into the static racing line (for CTE gate)
        self.delta_prev = 0.0
        self.a_prev = 0.0
        self.u_mean = np.zeros((2, self.N))  # warm-start [delta(N), accel(N)]
        self.consec_failures = 0
        self.mode = MODE_NORMAL

        # Residual learner (delay sized by 1/system_frequency) 
        solve_dt = 1.0 / float(node.get_parameter("system_frequency").value) \
            if node is not None else self.dt
        residual_params = {
            k[len("residual."):]: v for k, v in params.items()
            if k.startswith("residual.")
        }
        self.residual = ResidualLearner(residual_params, solve_dt)
        self._nom_steps = max(1, int(round(self.residual.target_horizon_s / self.dt)))
        self._steer_hist = deque([0.0] * NUM_STEER_HIST, maxlen=NUM_STEER_HIST)
        self._throttle_hist = deque([0.0] * NUM_THROTTLE_HIST, maxlen=NUM_THROTTLE_HIST)
        # Pose history covers v_window_s of past samples at the solve cadence.
        pose_hist_len = max(2, int(round(self.v_window_s / solve_dt)) + 2)
        self._pose_hist = deque(maxlen=pose_hist_len)  # (now_ns, s, d)

        # Telemetry publisher
        self.status_pub = None
        if node is not None:
            self.status_pub = node.create_publisher(Float32MultiArray, "mpc/status", 5)

        # Reusable rng
        self._rng = np.random.default_rng(0)

    # plan
    def plan(self, inputs: PlannerInputs) -> Optional[Tuple[float, float]]:
        t0 = time.perf_counter()
        x, y = inputs.pose_xy
        yaw = inputs.yaw_rad
        v = max(0.0, inputs.speed_mps)

        # Frenet against the STATIC racing line so the rejoin gate uses
        #    CTE-to-line, not CTE-to-overlay.
        self._set_active_line(self._static_arrays)
        _, d_static, j_static, _, _ = self._frenet(x, y, self.static_closest_idx)
        self.static_closest_idx = j_static

        # Drive overlay activation / deactivation off CTE-to-line.
        was_active = self.line_manager.is_active
        kart_state = KartState(
            xy=(x, y), yaw=yaw, speed_mps=v,
            closest_idx=self.static_closest_idx,
            cross_track_error=abs(d_static),
        )
        self.line_manager.update(kart_state)
        # Manager may snap closest_idx to merge_idx on deactivation.
        self.static_closest_idx = kart_state.closest_idx
        now_active = self.line_manager.is_active

        # On state transitions: rebuild bezier arrays / reset warm-start.
        if now_active and not was_active:
            self._bezier_arrays = self._build_line_arrays(
                self.line_manager.dynamic_line
            )
            self.closest_idx = 0
            self._reset_warm_start()
        elif was_active and not now_active:
            self.closest_idx = int(self.line_manager.merge_idx)
            self._bezier_arrays = None
            self._reset_warm_start()

        # Point Frenet reference at the active line (bezier or static).
        if now_active and self._bezier_arrays is not None:
            self._set_active_line(self._bezier_arrays)
        else:
            self._set_active_line(self._static_arrays)

        s, d, j_now, psi_track, _ = self._frenet(x, y, self.closest_idx)
        self.closest_idx = j_now

        # Track pose history for v_s / v_d estimates
        self._pose_hist.append((inputs.now_ns, s, d))
        v_s, v_d = self._frenet_velocity()

        # Speed target: the bezier carries its own vx ramp, so the per-step
        # v_ref = min(j_vx, v_target) inside _solve picks that up automatically.
        v_target = self.target_speed
        v_cap = self.v_max

        # Build candidate trajectories, evaluate, pick best
        zeros_breakdown = (0.0,) * 12
        try:
            best_u, best_cost, traj, feasible, breakdown = self._solve(
                x, y, yaw, v, j_now, v_target, v_cap,
            )
        except Exception:
            # NaN propagation - skip
            best_u, best_cost, traj, feasible = None, float("inf"), None, False
            breakdown = zeros_breakdown

        if not feasible or best_u is None:
            self.consec_failures += 1
            if self.consec_failures >= self.max_failures:
                self.mode = MODE_FAILSAFE
            self._publish_status(self.mode, False, t0, s, d, psi_track, v, v_target,
                                 0.0, 0.0, best_cost, 0.0,
                                 breakdown=breakdown)
            return 0.0, 0.0

        self.consec_failures = 0
        delta_cmd = float(best_u[0, 0])
        accel_cmd = float(best_u[1, 0])

        v_ref_now = min(float(self.l_vx[j_now]), self.target_speed)
        v_ref_now = max(0.0, min(self.v_max, v_ref_now))
        throttle_mps = v_ref_now
        steering_deg = math.degrees(delta_cmd)

        # Update warm-start (shift by 1)
        self.u_mean[:, :-1] = best_u[:, 1:]
        self.u_mean[:, -1] = best_u[:, -1]
        self.delta_prev = delta_cmd
        self.a_prev = accel_cmd
        self._steer_hist.appendleft(delta_cmd)
        self._throttle_hist.appendleft(accel_cmd)

        # Residual learner (shadow) 
        # nominal (held-command - straight line no acceleration) prediction over target_horizon_s of motion.
        nom_x, nom_y = self._hold_rollout(x, y, yaw, v, delta_cmd, accel_cmd, self._nom_steps)
        nom_s, nom_d, _, _, _ = self._frenet(nom_x, nom_y, j_now)
        kappa_local = self._curvature_at(j_now)
        phi = _features(
            d, v_s, v_d, kappa_local,
            tuple(self._steer_hist), tuple(self._throttle_hist),
            nom_s - s, nom_d - d,
        )
        self.residual.push(phi, s, d, nom_s - s, nom_d - d, v)
        self.residual.step(s, d)
        res_ps, res_pd = self.residual.predict(phi)

        # Telemetry
        margin_min = self.corridor_half - float(np.max(np.abs(traj["d"])))
        self._publish_status(self.mode, True, t0, s, d, psi_track, v, v_target,
                             delta_cmd, accel_cmd, best_cost, margin_min,
                             res_ps, res_pd,
                             breakdown=breakdown)

        return throttle_mps, steering_deg

    # helpers
    def _frenet(self, x: float, y: float, hint: int):
        """Returns (s, d, idx, psi_track, kappa). d is signed (left positive).

        Windowed search around `hint`, with a full-line resync when the windowed match is unreliable"""
        lo = max(0, hint - self.proj_back)
        hi = min(self.line_n, hint + self.proj_fwd)
        dx = self.l_x[lo:hi] - x
        dy = self.l_y[lo:hi] - y
        d2 = dx * dx + dy * dy
        j_rel = int(np.argmin(d2))
        j = lo + j_rel
        best_d2 = float(d2[j_rel])

        at_lo_edge = (j == lo and lo > 0)
        at_hi_edge = (j == hi - 1 and hi < self.line_n)
        # On a closed loop, the natural "window edge" near the seam is the last index of the array
        near_seam = self.line_closed and (
            hint <= self.proj_back or hint >= self.line_n - self.proj_back
        )
        if at_lo_edge or at_hi_edge or near_seam or best_d2 > self._resync_dist2:
            all_dx = self.l_x - x
            all_dy = self.l_y - y
            all_d2 = all_dx * all_dx + all_dy * all_dy
            j_full = int(np.argmin(all_d2))
            if float(all_d2[j_full]) + 1e-6 < best_d2:
                j = j_full

        psi_j = self.l_psi[j]
        cpsi, spsi = math.cos(psi_j), math.sin(psi_j)
        ex, ey = x - self.l_x[j], y - self.l_y[j]
        along = ex * cpsi + ey * spsi
        lateral = -ex * spsi + ey * cpsi
        return self.l_s[j] + along, lateral, j, psi_j, 0.0

    def _curvature_at(self, j: int) -> float:
        if 0 < j < self.line_n - 1:
            dpsi = _wrap(self.l_psi[j + 1] - self.l_psi[j - 1])
            ds = max(1e-3, self.l_s[j + 1] - self.l_s[j - 1])
            return float(dpsi / ds)
        return 0.0

    @staticmethod
    def _build_line_arrays(line: list) -> dict:
        """Convert waypoint rows (s,x,y,psi,kappa,vx) into flat numpy arrays
        with a finite-difference psi tangent recomputed from xy."""
        L = np.asarray([list(r[:6]) for r in line], dtype=np.float64)
        n = L.shape[0]
        l_s = L[:, 0]
        l_x = L[:, 1]
        l_y = L[:, 2]
        l_vx = L[:, 5]
        dx = np.empty_like(l_x)
        dy = np.empty_like(l_y)
        dx[1:-1] = l_x[2:] - l_x[:-2]
        dy[1:-1] = l_y[2:] - l_y[:-2]
        dx[0] = l_x[1] - l_x[0]
        dy[0] = l_y[1] - l_y[0]
        dx[-1] = l_x[-1] - l_x[-2]
        dy[-1] = l_y[-1] - l_y[-2]
        l_psi = np.arctan2(dy, dx)
        # Closed if first and last waypoints sit on top of each other (within
        # 2m). Used by _frenet to force a full-line resync near the seam.
        closed = bool(
            n >= 4
            and math.hypot(float(l_x[0] - l_x[-1]), float(l_y[0] - l_y[-1])) < 2.0
        )
        return {
            "n": n, "s": l_s, "x": l_x, "y": l_y, "vx": l_vx, "psi": l_psi,
            "closed": closed,
        }

    def _set_active_line(self, arrays: dict) -> None:
        self.line_n = arrays["n"]
        self.l_s = arrays["s"]
        self.l_x = arrays["x"]
        self.l_y = arrays["y"]
        self.l_vx = arrays["vx"]
        self.l_psi = arrays["psi"]
        self.line_closed = bool(arrays.get("closed", False))

    def _reset_warm_start(self) -> None:
        self.u_mean[:] = 0.0
        self.delta_prev = 0.0
        self.a_prev = 0.0
        self._pose_hist.clear()

    def _frenet_velocity(self) -> Tuple[float, float]:
        """Finite-difference (s, d) over `v_window_s` of pose history."""
        if len(self._pose_hist) < 2:
            return 0.0, 0.0
        now_ns, s_now, d_now = self._pose_hist[-1]
        target = now_ns - int(self.v_window_s * 1e9)
        ref = self._pose_hist[0]
        for entry in self._pose_hist:
            if entry[0] >= target:
                ref = entry
                break
        dt = (now_ns - ref[0]) / 1e9
        if dt <= 0.0:
            return 0.0, 0.0
        return (s_now - ref[1]) / dt, (d_now - ref[2]) / dt

    def _hold_rollout(self, x, y, yaw, v, delta, a, n):
        """Single-trajectory bicycle rollout — used by the residual learner."""
        for _ in range(n):
            x += self.dt * v * math.cos(yaw)
            y += self.dt * v * math.sin(yaw)
            yaw += self.dt * v / self.wheelbase * math.tan(delta)
            v = max(0.0, min(self.v_max, v + self.dt * a))
        return x, y

    # solve
    def _solve(self, x0, y0, yaw0, v0, j_now, v_target, v_cap):
        K, N, dt = self.K, self.N, self.dt
        rng = self._rng

        # Sample around warm-start mean. Sample[0] is the warm-start itself
        # so we never get worse than holding the previous plan.
        noise_d = rng.normal(0.0, self.steer_sigma, size=(K, N))
        noise_a = rng.normal(0.0, self.accel_sigma, size=(K, N))
        noise_d[0] = 0.0
        noise_a[0] = 0.0
        delta_seq = self.u_mean[0, :] + noise_d
        accel_seq = self.u_mean[1, :] + noise_a
        # Steering rate limit enforced sequentially per step
        dr_max = self.steer_rate_max * dt
        prev_d = np.full(K, self.delta_prev)
        for k in range(N):
            lo = prev_d - dr_max
            hi = prev_d + dr_max
            np.clip(delta_seq[:, k], np.maximum(lo, -self.steer_max),
                    np.minimum(hi, self.steer_max), out=delta_seq[:, k])
            prev_d = delta_seq[:, k]
        np.clip(accel_seq, self.a_min, self.a_max, out=accel_seq)

        # Vectorized bicycle rollout
        tx = np.empty((K, N))
        ty = np.empty((K, N))
        tpsi = np.empty((K, N))
        tv = np.empty((K, N))
        x = np.full(K, x0)
        y = np.full(K, y0)
        psi = np.full(K, yaw0)
        v = np.full(K, v0)
        for k in range(N):
            d_k = delta_seq[:, k]
            a_k = accel_seq[:, k]
            x = x + dt * v * np.cos(psi)
            y = y + dt * v * np.sin(psi)
            psi = psi + dt * v / self.wheelbase * np.tan(d_k)
            v = np.clip(v + dt * a_k, 0.0, v_cap)
            tx[:, k] = x
            ty[:, k] = y
            tpsi[:, k] = psi
            tv[:, k] = v

        # Batched Frenet projection onto the windowed line slice ahead of j_now
        lo = max(0, j_now - self.proj_back)
        hi = min(self.line_n, j_now + self.proj_fwd)
        lx = self.l_x[lo:hi]
        ly = self.l_y[lo:hi]
        lp = self.l_psi[lo:hi]
        ls = self.l_s[lo:hi]
        lv = self.l_vx[lo:hi]
        # dx,dy: [K, N, M]
        dx = tx[..., None] - lx
        dy = ty[..., None] - ly
        d2 = dx * dx + dy * dy
        jmin = np.argmin(d2, axis=-1)
        j_psi = lp[jmin]
        j_s = ls[jmin]
        j_vx = lv[jmin]
        ex = tx - lx[jmin]
        ey = ty - ly[jmin]
        cpsi = np.cos(j_psi)
        spsi = np.sin(j_psi)
        s = j_s + ex * cpsi + ey * spsi
        d = -ex * spsi + ey * cpsi

        # Cost terms
        psi_err = _wrap(tpsi - j_psi)
        v_ref = np.minimum(j_vx, v_target)
        v_err = tv - v_ref

        d_diff = np.diff(delta_seq, axis=1, prepend=self.delta_prev)

        boundary = np.maximum(0.0, np.abs(d) - self.corridor_half)

        progress = s[:, -1] - s[:, 0]

        # Named cost components — also exported for diagnostics.
        a_lat = tv * tv * np.tan(delta_seq) / self.wheelbase
        edge_excess = np.maximum(0.0, np.abs(d) - self.edge_inner)
        c_d = self.w_d * np.sum(d * d, axis=1)
        c_h = self.w_heading * np.sum(psi_err * psi_err, axis=1)
        c_v = self.w_speed * np.sum(v_err * v_err, axis=1)
        c_delta = self.w_delta * np.sum(delta_seq * delta_seq, axis=1)
        c_drate = self.w_drate * np.sum(d_diff * d_diff, axis=1)
        c_accel = self.w_accel * np.sum(accel_seq * accel_seq, axis=1)
        c_bnd = self.w_boundary * np.sum(boundary * boundary, axis=1)
        c_edge = self.w_edge * np.sum(edge_excess * edge_excess, axis=1)
        c_prog = -self.w_progress * progress
        c_term_d = self.w_term_d * d[:, -1] ** 2
        c_term_h = self.w_term_h * psi_err[:, -1] ** 2
        c_alat = self.w_a_lat * np.sum(
            np.maximum(0.0, np.abs(a_lat) - self.a_lat_max) ** 2, axis=1,
        )
        cost = (c_d + c_h + c_v + c_delta + c_drate + c_accel
                + c_bnd + c_edge + c_prog + c_term_d + c_term_h + c_alat)

        # Corridor enforcement is a soft quadratic penalty (c_bnd above)
        best = int(np.argmin(cost))
        best_cost = float(cost[best])
        feasible = best_cost < self.feasibility_threshold
        u = np.stack([delta_seq[best], accel_seq[best]], axis=0)
        traj = {"d": d[best], "s": s[best]}
        breakdown = (
            float(c_d[best]), float(c_h[best]), float(c_v[best]),
            float(c_delta[best]), float(c_drate[best]), float(c_accel[best]),
            float(c_bnd[best]), float(c_prog[best]),
            float(c_term_d[best]), float(c_term_h[best]), float(c_alat[best]),
            float(c_edge[best]),
        )
        return u, best_cost, traj, feasible, breakdown

    #  telemetry
    def _publish_status(self, mode, success, t0, s, d, psi_track, v, v_target,
                        delta_cmd, accel_cmd, cost, margin_min,
                        res_s=0.0, res_d=0.0, breakdown=(0.0,) * 12):
        if self.status_pub is None:
            return
        solve_ms = (time.perf_counter() - t0) * 1000.0
        nom_s, nom_d, res_es, res_ed = self.residual.mean_error()
        payload = [
            float(mode), 1.0 if success else 0.0, solve_ms,
            float(s), float(d), float(psi_track), float(v), float(v_target),
            float(math.degrees(delta_cmd)), float(accel_cmd),
            float(cost) if math.isfinite(cost) else -1.0,
            float(margin_min),
            float(res_s), float(res_d),
            nom_s, nom_d, res_es, res_ed,
            float(self.residual.samples_trained),
            *breakdown,
        ]
        self.status_pub.publish(Float32MultiArray(data=payload))

    def dynamic_line_state(self) -> Optional[dict]:
        if self.line_manager.is_active:
            line = self.line_manager.dynamic_line
            return {
                "active": True,
                "strategy": type(self.line_manager.active_strategy).__name__,
                "merge_idx": int(self.line_manager.merge_idx),
                "points": [[float(p[1]), float(p[2])] for p in line],
            }
        return {"active": False, "strategy": None, "merge_idx": -1, "points": []}
