version: "3.8"

services:

  dev-jetson:
    container_name: ros2-dev-jetson
    hostname: jetson-dev
    environment:
      - TARGET_DEVICE=jetson
      - ROS_NETWORK_INTERFACE=enP8p1s0
      - ROS_DISTRO=humble
      - ROS_DOMAIN_ID=42
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///ws/docker/cyclonedds.xml
    # devices:
    #   - "/dev/ttyACM0:/dev/ttyACM0" # canable
    #   - "/dev/ttyTHS1:/dev/ttyTHS1" # GPS
    #   - "/dev/i2c-7:/dev/i2c-7"     # IMU
    image: ghcr.io/evc-purdue/ros2-humble-dev:main
    network_mode: host
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ../:/ws
      - ros_cache:/root/.cache
      - /data/kart_logs:/ws/logs
    ports:
      - "8000:8000"
    command: bash /ws/scripts/start.bash

  dev-rubik:
    container_name: ros2-dev-rubik
    hostname: rubik-dev
    environment:
      - TARGET_DEVICE=rubik
      - ROS_NETWORK_INTERFACE=enxf074e47f50f9
      - ROS_DISTRO=humble
      - ROS_DOMAIN_ID=42
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///ws/docker/cyclonedds.xml
    # devices:
    #   - "/dev/video0:/dev/video0"
    image: ghcr.io/evc-purdue/ros2-humble-dev:main
    network_mode: host
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ../:/ws
      - ros_cache:/root/.cache
      - /data/kart_logs:/ws/logs
    ports:
      - "8000:8000"
    command: bash /ws/scripts/start.bash

volumes:
  ros_cache: